---

name: clion-nsg
version: '2017.1.3'
summary: A cross-platform IDE for C and C++
description: |
  CLion is a cross-platform IDE for C and C++ from JetBrains based on
  IntelliJ IDEA. This snap do not contain the actual binary, it's
  downloaded from jetbrains.com on first run. This is an unofficial package.

grade: stable
confinement: strict

parts:
  clion:
    plugin: dump
    source: src
